dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make -j2
  - CTEST_OUTPUT_ON_FAILURE=1 make test
addons:
  apt:
    packages:
      - cmake
      - gcc-5
      - g++-5
      - cmake-data
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
      - libopenmpi1.6
