dist: trusty
sudo: false
language: cpp
compiler:
  - gcc
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make -j2
  - CTEST_OUTPUT_ON_FAILURE=1 make test
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - openmpi-bin
      - openmpi-common
      - libopenmpi-dev
      - libopenmpi1.6
